### ISSUE TITLE
Your web app is ready! 🚀

### ISSUE THREAD

**Issue by sleepingexperiments** [GabPSS/HomeworkPlanner#151]
Hey! 👋

Someone has requested a demo of your project using [Ukoreh](https://ukoreh.fun/)! 🧙‍♂️.

The app compiled fine and is now live at https://flutter-preview.github.io/GabPSS-HomeworkPlanner

**Comment by GabPSS** [comment]
Interesting.. Might consider converting it into a PWA in the future, could be a good choice of platform maybe?
